<?php
	DEFINE('PAGE_PATH','pages');
	DEFINE('ERROR_PAGE','404.php');
	DEFINE('HOME_PAGE','home.php');
	
	DEFINE('MYSQL_HOST','127.0.0.1');
	DEFINE('MYSQL_USERNAME','root');
	DEFINE('MYSQL_PASSWORD','');
	DEFINE('MYSQL_DATABASE','pp');
?>